
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grtqfffyhtblqkcmqifb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdydHFmZmZ5aHRibHFrY21xaWZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NzU3NDIsImV4cCI6MjA1NzU1MTc0Mn0.14KLFvI6YFvc2DuJ2CSrKVaNlqGyAmJnXrj_1usN69Y";

// Configure the Supabase client with persistence options
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      storageKey: 'sportyfi-auth-token',
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce'
    }
  }
);

// Add custom type helpers
export type Tables = Database['public']['Tables'];
export type Match = Tables['matches']['Row'];
export type Participant = Tables['participants']['Row'];
export type Profile = Tables['profiles']['Row'];
export type ParticipantWithProfile = Participant & { profile: Profile | null };

// Add new type helpers for venues and bookings
export type Venue = Tables['venues']['Row'];
export type VenueSport = Tables['venue_sports']['Row'];
export type VenueAmenity = Tables['venue_amenities']['Row'];
export type VenueImage = Tables['venue_images']['Row'];
export type Booking = Tables['bookings']['Row'];
export type VenueRequest = Tables['venue_requests']['Row'];

// Complete venue type with relations
export type VenueWithRelations = Venue & {
  sports?: VenueSport[];
  amenities?: VenueAmenity[];
  images?: VenueImage[];
};

// Profile avatar helpers
export async function uploadAvatar(userId: string, file: File) {
  if (!userId) {
    throw new Error('User ID is required for avatar upload');
  }
  
  if (!file) {
    throw new Error('File is required for avatar upload');
  }
  
  const fileExt = file.name.split('.').pop();
  const timestamp = Date.now(); // Add timestamp for uniqueness and cache busting
  const fileName = `${userId}-${timestamp}.${fileExt}`;
  const filePath = `${fileName}`;

  try {
    const { error: uploadError, data: uploadData } = await supabase.storage
      .from('profiles')
      .upload(filePath, file, { upsert: true });

    if (uploadError) {
      console.error('Error uploading avatar:', uploadError);
      throw new Error(uploadError.message || 'Failed to upload avatar');
    }

    if (!uploadData) {
      throw new Error('No data returned from upload');
    }

    const { data } = supabase.storage
      .from('profiles')
      .getPublicUrl(filePath);

    if (!data || !data.publicUrl) {
      throw new Error('Failed to get public URL for avatar');
    }

    return data.publicUrl;
  } catch (error) {
    console.error('Exception during avatar upload:', error);
    throw error;
  }
}

export async function updateProfile(userId: string, updates: Partial<Profile>) {
  if (!userId) {
    throw new Error('User ID is required for profile update');
  }
  
  try {
    const { error } = await supabase
      .from('profiles')
      .update(updates)
      .eq('id', userId);

    if (error) {
      console.error('Error updating profile:', error);
      throw error;
    }
  } catch (error) {
    console.error('Exception during profile update:', error);
    throw error;
  }
}
