
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grtqfffyhtblqkcmqifb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdydHFmZmZ5aHRibHFrY21xaWZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NzU3NDIsImV4cCI6MjA1NzU1MTc0Mn0.14KLFvI6YFvc2DuJ2CSrKVaNlqGyAmJnXrj_1usN69Y";

// Configure the Supabase client with persistence options
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      storageKey: 'sportyfi-auth-token',
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce'
    }
  }
);

// Add custom type helpers
export type Tables = Database['public']['Tables'];
export type Match = Tables['matches']['Row'];
export type Participant = Tables['participants']['Row'];
export type Profile = Tables['profiles']['Row'];
